version: '3'
name: PRODUCTION_api_christopherwood_dev

volumes:
  data:

services:
  api:
    build:
      dockerfile: ./docker/node/Dockerfile.prod.node
    volumes:
    - ./src:/usr/src/app/src
    image: node_api
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis:7.0.3-alpine
    restart: always
    volumes:
      - data:/data
    expose:
      - "6379"
  db:
    # platform: linux/amd64
    image: mysql:8.0.30-debian
    restart: always
    expose:
    - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file: 
      - .env