version: '3'
name: DEVELOPMENT_api_christopherwood_dev

volumes:
  data:

services:
  api:
    build:
      dockerfile: ./docker/node/Dockerfile.dev.node
    volumes:
    - ./src:/usr/src/app/src
    image: node_api
    restart: always
    ports:
      - 8080:8080
    env_file: 
      - .env
    depends_on:
      - "mongodb"
  redis:
    image: redis:7.0.3-alpine
    restart: always
    volumes:
      - data:/data
    expose:
      - "6379"
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    expose:
      - "27017"
    ports:
      - "27017:27017"
    env_file:
      - .env