version: '3'
name: api_christopherwood_dev

volumes:
  data:

services:
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile.nginx
    ports:
      - "80:80"
  node:
    build:
      dockerfile: ./docker/node/Dockerfile.node
    expose:                 # <--- the important bit here
      - "8080"
  # db:
  #   image: mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password1
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=password2
  #     - MYSQL_DATABASE=database
  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379