version: '3'
name: PRODUCTION_api_christopherwood_dev

volumes:
  data:

services:
  api:
    build:
      dockerfile: ./docker/node/Dockerfile.prod.node
    volumes:
    - ./src:/usr/src/app/src
    image: node_api
    restart: always
    ports:
      - 8080:8080
    env_file: 
      - .env
    depends_on:
      - "mongodb"
  redis:
    image: redis:7.0.3-alpine
    restart: always
    volumes:
      - data:/data
    expose:
      - "6379"
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    expose:
      - "27017"
    ports:
      - "27017:27017"
    env_file:
      - .env
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
        - mongodb
    ports:
      - 8081:8081