FROM node:16.16.0-alpine

WORKDIR /usr/src/app

ENV NODE_ENV=development                                                                                                       
COPY package*.json ./
RUN npm install

COPY . .

CMD [ "npm", "run-script", "dev" ]
