FROM node:16.16-alpine

WORKDIR /usr/src/app

RUN npm i -g nodemon
COPY package*.json ./
RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

CMD [ "nodemon", "./api/index.js" ]