# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to deploy on remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: ${{ secrets.DEPLOY_SCRIPT }}
