# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to deploy on remote host
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey: ${{ secrets.SSH_KEY }}
        command: whoami
